import { Job, Settings } from './types';

export const CATEGORIES: { name: string; icon: string; color: string }[] = [
  { name: 'ITI Jobs', icon: 'construct', color: '#1D4ED8' },
  { name: 'Engineering', icon: 'cog', color: '#0891B2' },
  { name: 'Computer/IT', icon: 'laptop', color: '#7C3AED' },
  { name: 'Office Jobs', icon: 'briefcase', color: '#D97706' },
  { name: 'Sales & Marketing', icon: 'megaphone', color: '#DC2626' },
  { name: 'Banking & Finance', icon: 'card', color: '#16A34A' },
  { name: 'Healthcare', icon: 'medkit', color: '#DB2777' },
  { name: 'Teaching', icon: 'school', color: '#2563EB' },
  { name: 'Government Jobs', icon: 'business', color: '#4338CA' },
  { name: 'Private Jobs', icon: 'person', color: '#0D9488' },
  { name: 'Apprenticeship', icon: 'hammer', color: '#EA580C' },
  { name: 'Internship', icon: 'ribbon', color: '#9333EA' },
  { name: 'Part-Time', icon: 'time', color: '#0284C7' },
  { name: 'Work From Home', icon: 'home', color: '#059669' },
];

export const LOCATIONS = [
  'Raigarh',
  'Kharsia',
  'Gharghoda',
  'Sarangarh',
  'Tamnar',
  'Pusaur',
  'Lailunga',
  'Dharamjaigarh',
  'Bilaspur',
  'Raipur',
  'Korba',
  'Work From Home',
];

export const DEFAULT_SETTINGS: Settings = {
  brand: 'Jobs at Raigarh',
  tagline: 'Connecting Talent with Opportunities',
  founder: 'Abhishek Swarnkar',
  email: 'abhixfactor@gmail.com',
  phone: '+91 90000 00000',
  address: 'Raigarh, Chhattisgarh, India',
  about:
    'Jobs at Raigarh is a local job consultancy platform helping job seekers discover employment opportunities and helping employers connect with suitable candidates.',
};

export const ADMIN_SEED = {
  name: 'Abhishek Swarnkar',
  email: 'abhixfactor@gmail.com',
  phone: '+91 90000 00000',
  password: 'admin123',
};

const DAY = 24 * 60 * 60 * 1000;
const now = Date.now();

function job(p: Partial<Job> & { title: string; company: string }): Job {
  return {
    id: 'job_' + Math.random().toString(36).slice(2, 10),
    logo: '🏢',
    location: 'Raigarh',
    category: 'Private Jobs',
    jobType: 'Full Time',
    salary: '₹15,000 - ₹25,000 / month',
    experience: '1-3 years',
    education: 'Graduate',
    skills: [],
    vacancies: 2,
    description: '',
    responsibilities: [],
    benefits: [],
    qualification: '',
    contact: 'abhixfactor@gmail.com',
    postedAt: now - 3 * DAY,
    deadline: now + 20 * DAY,
    status: 'published',
    featured: false,
    isDemo: true,
    ...p,
  } as Job;
}

export const SEED_JOBS: Job[] = [
  job({
    title: 'ITI Fitter — Rolling Mill',
    company: 'Jindal Steel & Power',
    logo: '🏭',
    location: 'Raigarh',
    category: 'ITI Jobs',
    jobType: 'Full Time',
    salary: '₹18,000 - ₹28,000 / month',
    experience: '0-2 years',
    education: 'ITI (Fitter)',
    skills: ['Fitter', 'Machine Maintenance', 'Safety', 'Blueprint Reading'],
    vacancies: 8,
    featured: true,
    postedAt: now - 1 * DAY,
    deadline: now + 25 * DAY,
    description:
      'We are hiring ITI Fitters for our rolling mill operations at Raigarh plant. Freshers with ITI Fitter trade are welcome.',
    responsibilities: [
      'Assemble, install and maintain mechanical equipment',
      'Perform routine preventive maintenance',
      'Follow all plant safety protocols',
    ],
    benefits: ['PF & ESI', 'Canteen', 'Free Transport', 'Medical Insurance'],
    qualification: 'ITI in Fitter trade from a recognized institute',
    contact: 'hr.raigarh@jspl.com',
  }),
  job({
    title: 'Junior Mechanical Engineer',
    company: 'Adhunik Power',
    logo: '⚙️',
    location: 'Tamnar',
    category: 'Engineering',
    salary: '₹25,000 - ₹40,000 / month',
    experience: '1-3 years',
    education: 'B.E / B.Tech (Mechanical)',
    skills: ['AutoCAD', 'Maintenance', 'Thermal Plant', 'Problem Solving'],
    vacancies: 3,
    featured: true,
    postedAt: now - 2 * DAY,
    description:
      'Looking for a Junior Mechanical Engineer to support operations and maintenance at our thermal power facility.',
    responsibilities: [
      'Supervise maintenance activities',
      'Prepare technical reports',
      'Coordinate with vendors',
    ],
    benefits: ['PF', 'Accommodation', 'Performance Bonus'],
    qualification: 'B.E/B.Tech in Mechanical Engineering',
  }),
  job({
    title: 'Full Stack Developer',
    company: 'TechNova Solutions',
    logo: '💻',
    location: 'Work From Home',
    category: 'Computer/IT',
    jobType: 'Work From Home',
    salary: '₹35,000 - ₹60,000 / month',
    experience: '2-4 years',
    education: 'B.Tech / MCA',
    skills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript', 'REST API'],
    vacancies: 2,
    featured: true,
    postedAt: now - 1 * DAY,
    description:
      'Remote full stack developer role building modern web applications. Flexible timing, product-focused team.',
    responsibilities: [
      'Develop and maintain web applications',
      'Design REST APIs and database schemas',
      'Write clean, testable code',
    ],
    benefits: ['Work From Home', 'Flexible Hours', 'Learning Budget'],
    qualification: 'B.Tech/MCA or equivalent experience',
  }),
  job({
    title: 'Office Assistant / Data Entry',
    company: 'Raigarh Traders Association',
    logo: '🗂️',
    location: 'Raigarh',
    category: 'Office Jobs',
    salary: '₹12,000 - ₹16,000 / month',
    experience: '0-1 years',
    education: '12th Pass / Graduate',
    skills: ['MS Excel', 'Typing', 'Documentation', 'Hindi & English'],
    vacancies: 4,
    postedAt: now - 4 * DAY,
    description:
      'Data entry and general office administration work. Good typing speed and computer knowledge required.',
    responsibilities: [
      'Maintain records and files',
      'Data entry in Excel and portal',
      'Handle front office coordination',
    ],
    benefits: ['Fixed Hours', 'Weekly Off'],
    qualification: 'Minimum 12th pass with computer knowledge',
  }),
  job({
    title: 'Sales Executive (Field)',
    company: 'Bharat Electronics Store',
    logo: '📣',
    location: 'Kharsia',
    category: 'Sales & Marketing',
    salary: '₹14,000 + Incentives',
    experience: '0-2 years',
    education: '12th / Graduate',
    skills: ['Communication', 'Negotiation', 'Field Sales', 'Two Wheeler'],
    vacancies: 6,
    postedAt: now - 5 * DAY,
    description:
      'Field sales executive for consumer electronics. Attractive incentives on target achievement.',
    responsibilities: [
      'Meet daily sales targets',
      'Build customer relationships',
      'Report daily activities',
    ],
    benefits: ['Incentives', 'Travel Allowance'],
    qualification: '12th pass, two wheeler with license',
  }),
  job({
    title: 'Bank Relationship Officer',
    company: 'Chhattisgarh Rural Bank',
    logo: '🏦',
    location: 'Raigarh',
    category: 'Banking & Finance',
    salary: '₹20,000 - ₹30,000 / month',
    experience: '1-3 years',
    education: 'Graduate (Any)',
    skills: ['CASA', 'Customer Service', 'Cross Selling', 'MS Office'],
    vacancies: 3,
    postedAt: now - 6 * DAY,
    description:
      'Manage customer relationships and drive banking product sales at branch level.',
    responsibilities: [
      'Open new accounts (CASA)',
      'Cross-sell banking products',
      'Ensure customer satisfaction',
    ],
    benefits: ['PF', 'Incentives', 'Career Growth'],
    qualification: 'Any graduate with good communication',
  }),
  job({
    title: 'Staff Nurse (GNM)',
    company: 'OP Jindal Hospital',
    logo: '🏥',
    location: 'Raigarh',
    category: 'Healthcare',
    salary: '₹18,000 - ₹26,000 / month',
    experience: '0-3 years',
    education: 'GNM / B.Sc Nursing',
    skills: ['Patient Care', 'Emergency', 'Injections', 'Record Keeping'],
    vacancies: 5,
    featured: true,
    postedAt: now - 2 * DAY,
    description:
      'Staff nurses required for a multi-specialty hospital. Rotational shifts.',
    responsibilities: [
      'Provide bedside patient care',
      'Assist doctors during procedures',
      'Maintain patient records',
    ],
    benefits: ['Accommodation', 'PF', 'Medical'],
    qualification: 'GNM or B.Sc Nursing with CG Nursing Council registration',
  }),
  job({
    title: 'Primary School Teacher',
    company: 'Delhi Public School Raigarh',
    logo: '🎓',
    location: 'Raigarh',
    category: 'Teaching',
    salary: '₹18,000 - ₹28,000 / month',
    experience: '1-4 years',
    education: 'B.Ed / D.El.Ed',
    skills: ['Classroom Management', 'English', 'Lesson Planning', 'Patience'],
    vacancies: 4,
    postedAt: now - 3 * DAY,
    description:
      'Enthusiastic primary teachers to join a reputed CBSE school. Strong English communication required.',
    responsibilities: [
      'Plan and deliver engaging lessons',
      'Assess and track student progress',
      'Coordinate with parents',
    ],
    benefits: ['PF', 'Summer Break', 'Training'],
    qualification: 'Graduate with B.Ed / D.El.Ed',
  }),
  job({
    title: 'Electrician Apprentice',
    company: 'Raigarh Power Works',
    logo: '🔌',
    location: 'Gharghoda',
    category: 'Apprenticeship',
    jobType: 'Apprenticeship',
    salary: '₹9,000 - ₹12,000 / month (Stipend)',
    experience: 'Fresher',
    education: 'ITI (Electrician)',
    skills: ['Wiring', 'Electrical Safety', 'Motor Repair'],
    vacancies: 10,
    postedAt: now - 7 * DAY,
    description:
      'Apprenticeship program for ITI Electricians with on-the-job training and certification.',
    responsibilities: [
      'Assist senior electricians',
      'Learn plant electrical systems',
      'Follow safety norms',
    ],
    benefits: ['Stipend', 'Certificate', 'PPE Provided'],
    qualification: 'ITI Electrician, age 18-25',
  }),
  job({
    title: 'Digital Marketing Intern',
    company: 'GrowthHive Media',
    logo: '📱',
    location: 'Work From Home',
    category: 'Internship',
    jobType: 'Internship',
    salary: '₹6,000 - ₹10,000 / month (Stipend)',
    experience: 'Fresher',
    education: 'Pursuing / Graduate',
    skills: ['Social Media', 'Canva', 'Content Writing', 'SEO Basics'],
    vacancies: 3,
    postedAt: now - 2 * DAY,
    description:
      'Remote internship in digital marketing. Great for students and freshers wanting real experience.',
    responsibilities: [
      'Create social media content',
      'Assist in ad campaigns',
      'Track basic analytics',
    ],
    benefits: ['Work From Home', 'Certificate', 'Flexible'],
    qualification: 'Any graduate/pursuing with interest in marketing',
  }),
  job({
    title: 'Delivery Partner (Part-Time)',
    company: 'QuickCart Logistics',
    logo: '🛵',
    location: 'Raigarh',
    category: 'Part-Time',
    jobType: 'Part Time',
    salary: '₹8,000 - ₹15,000 / month',
    experience: 'Fresher',
    education: 'No formal education',
    skills: ['Two Wheeler', 'Local Area Knowledge', 'Punctual'],
    vacancies: 15,
    postedAt: now - 1 * DAY,
    description:
      'Flexible part-time delivery work. Choose your own hours. Weekly payouts.',
    responsibilities: [
      'Pick up and deliver orders on time',
      'Maintain delivery quality',
    ],
    benefits: ['Weekly Payout', 'Flexible Hours', 'Fuel Bonus'],
    qualification: 'Own two wheeler with valid license',
  }),
  job({
    title: 'Government Data Operator (Contract)',
    company: 'District Collectorate Raigarh',
    logo: '🏛️',
    location: 'Raigarh',
    category: 'Government Jobs',
    jobType: 'Contract',
    salary: '₹16,000 - ₹20,000 / month',
    experience: '1-2 years',
    education: 'Graduate + CPCT',
    skills: ['CPCT', 'Typing (Hindi/English)', 'MS Office', 'e-Governance'],
    vacancies: 5,
    postedAt: now - 8 * DAY,
    deadline: now + 12 * DAY,
    description:
      'Contractual data entry operators for district e-governance projects. CPCT certification mandatory.',
    responsibilities: [
      'Digitize government records',
      'Operate e-governance portals',
      'Maintain data accuracy',
    ],
    benefits: ['Government Project', 'Fixed Hours'],
    qualification: 'Graduate with valid CPCT certificate',
  }),
  job({
    title: 'Accountant (Tally)',
    company: 'Sarangarh Cements',
    logo: '🧮',
    location: 'Sarangarh',
    category: 'Banking & Finance',
    salary: '₹16,000 - ₹24,000 / month',
    experience: '2-5 years',
    education: 'B.Com',
    skills: ['Tally ERP', 'GST', 'Accounts Payable', 'Excel'],
    vacancies: 2,
    postedAt: now - 9 * DAY,
    description:
      'Experienced accountant for day-to-day accounting, GST filing and reconciliation.',
    responsibilities: [
      'Maintain books of accounts in Tally',
      'File GST returns',
      'Bank reconciliation',
    ],
    benefits: ['PF', 'Bonus'],
    qualification: 'B.Com with Tally and GST knowledge',
  }),
  job({
    title: 'CNC Operator',
    company: 'Lailunga Engineering Works',
    logo: '🛠️',
    location: 'Lailunga',
    category: 'ITI Jobs',
    salary: '₹17,000 - ₹27,000 / month',
    experience: '1-3 years',
    education: 'ITI / Diploma',
    skills: ['CNC Programming', 'Turning', 'Measurement', 'Quality Check'],
    vacancies: 4,
    postedAt: now - 10 * DAY,
    description:
      'CNC machine operators for precision component manufacturing.',
    responsibilities: [
      'Operate CNC machines',
      'Read engineering drawings',
      'Ensure quality standards',
    ],
    benefits: ['PF', 'Overtime Pay'],
    qualification: 'ITI/Diploma with CNC experience',
  }),
];
